server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzyybs/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: master
#rabbitmq相关配置
  rabbitmq:
    host: mintv.com
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
#repositry更新之后，center获知。
#   通知所有client：post -> http://localhost:3344/actuatorbus-refresh/
#   定点通知client：post -> http://localhost:3344/actuatorbus-refresh/{spring.application.name}:{server.port}
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'